name: test push kubernetes images

env:
  KubernetesVersion: 1.26.4

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3


      - name: publish kubernetes images
        run: chmod +x ./app && ./app -v 2 --kubernetes-version v${{ env.KubernetesVersion }}
